### ISSUE TITLE
Fix: TravelLocation 삭제 요청 시 아이디로 Location을 찾을 수 없는 버그

### ISSUE THREAD

**Issue by MackoLee** [travel-duo/travel-duo-server#44]
## 버그 설명
![image](https://github.com/user-attachments/assets/6b4d5034-b0f3-453d-b357-b820de150e21)

delete /travel-locations/:id 요청 하면 해당아이디를 찾을 수 없다고 뜸.

## 재현 방법
위와 같음

**Comment by MackoLee** [comment]
갑자기 삭제가 정상적으로 되네요..

**Comment by CheolHo-0428** [comment]
> 갑자기 삭제가 정상적으로 되네요..

? 그럼 우선 보류..... 다른거 먼저 할게
